### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by endorphinians** [malaysia-ai/aws-access#3]
**What is your name?**
Farhan

**What is your email address (if you are not comfortable to share in public issue, private message https://github.com/oscarnz discord)? This is to invite AWS for the first time.**
endorphinians@gmail.com

**What access you need? If you got this access, you have to teach back to the community what you already done.**
Be very specific, eg, AWS Glue, EKS.
Not really sure. AWS is confusing. Having this idea of an AI dictionary - thesaurus - etymology- glossary - vocabulary - grammar. Not a techie but AI taught me what HTML stands for and now I know how to use <div><h1>Java sucks !</h1></div>. ChatGPT once explained why my 2016 Preve gear rammed upon changing and he told me to check on the torque-converter. I only know to convert kg to g. 

Safe to say that I might not know what php stands for but I have argued with AI and won.

**Comment by oscarnz** [comment]
You may want to explore aws services on google. Please be specific on your request. Thank you
